# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67740a6a0f742195127dec9caa2623f0e0a4f089941c5713d7b8587d25ae7de7a53d7d4ffd6e4a29f35c13b0a84a577ce9c8155700165d05598c9f496e1346d4

test:
  secret_key_base: 7db53b56fb6de9405100da85bbdb576a9dfc5754ee0c3b0474286bb5ad6b733ce954c21e58bd66ea8d694a7458a733654659161cbcf5ff29162bc2d8ea28a9d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
